// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kviekfwsfesuyaqkzzuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2aWVrZndzZmVzdXlhcWt6enVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NzM5NTEsImV4cCI6MjA3MzQ0OTk1MX0.b7vBFi6AWzWjmx1eMMRrFRiXd0CkkgPo_GeZSEQG1lQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});